### ISSUE TITLE
Obfuscated code == malware?

### ISSUE THREAD

**Issue by neitsab** [KhanhNguyen9872/http-share-termux#1]
Greetings,

Checking both `install.sh` and `bin/http-share.sh` shows obfuscated code without any explanation about it in the README.

My first reflex was to report the repository, but checking your account shows that you have other regular contributions, so I thought I'd first ask... What's the deal with the obfuscated code?

As a concerned netizen, that makes me *really* suspicious. Were you just flexing some code golfing skills?

If so, could you please add a mention of it and **how to deobfuscate the code** in the project's README?

Obviously you don't owe a random stranger anything, but failing that my only choice will be to report this strangeness to GitHub support.

All the best and sorry for the fuss if it's nothing.

**Comment by KhanhNguyen9872** [comment]
> 

no, it don't have malware
jf you want source code from this, i will update it into there when you reply this comment

**Comment by neitsab** [comment]
Well yes, I'm interested in using the software myself and would appreciate a de-obfuscated version of it, but that leaves us with this repo in its uncertain state for any potential other user not as cautious as I am... Why not make a comment about it in the README?

**Comment by KhanhNguyen9872** [comment]
> Well yes, I'm interested in using the software myself and would appreciate a de-obfuscated version of it, but that leaves us with this repo in its uncertain state for any potential other user not as cautious as I am... Why not make a comment about it in the README?

source code updated!
all repo from my git don't have any malware, then you can use it without any lost file or problem
